# ============================================
# WORKFLOW: Container Security
# ============================================
name: 🔒 Container Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ============================================
  # JOB: Lint Dockerfile com Hadolint
  # ============================================
  hadolint:
    name: 🔎 Dockerfile Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fiap-dclt-devsecops-aula04

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔎 Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.secure
          failure-threshold: warning